apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: GCPDemo
  name: GCPDemo
  namespace: default
spec:
  replicas: 2 
  minReadySeconds: 45
  selector:
    matchLabels:
      app: GCPDemo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: currency-conversion
    spec:
      containers:
      - image: aswinkum58/gcpdemo:0.0.1.RELEASE
        imagePullPolicy: IfNotPresent
        name: GCPDemo
        # env:
        #   - name: CURRENCY_EXCHANGE_SERVICE_HOST
        #     value: http://currency-exchange
        
        #     valueFrom: 
        #       configMapKeyRef:
        #         key: CURRENCY_EXCHANGE_SERVICE_HOST
        #         name: currency-conversion-config-map
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels: 
    app: GCPDemo
  name: GCPDemo
  namespace: default
spec:
  ports:
  - port: 8080 #CHANGE
    protocol: TCP
    targetPort: 8080 #CHANGE
  selector:
    app: GCPDemo
  sessionAffinity: None #CHANGE
  type: LoadBalancer